import {
  Globe, Settings, Receipt, Palette, TrendingUp, Megaphone, Building2, FileText, Users,
  Landmark, MapPin, Phone, Calculator, BadgeCheck, ShoppingCart, CreditCard, Search, Camera,
  Mail, Bot, Workflow, Presentation, Coins, GraduationCap, Crown,
} from "lucide-react";

/**
 * Servicios para empresas: fuente única para la tienda pública (/tienda) y la del portal (/portal/tienda).
 * Cada `id` debe existir en PRODUCT_CATALOG (src/lib/payments/product-catalog.ts), que es lo que cobra Stripe.
 */
export type BusinessService = {
  id: string; // debe existir en PRODUCT_CATALOG (src/lib/payments/product-catalog.ts)
  name: string;
  description: string;
  price: number;
  /** Precio de referencia en el mercado de EE. UU. (se muestra tachado). Debe ser un precio real comparable. */
  marketPrice: number;
  priceNote?: string; // "Desde", "/ mes" o "/ año"
  badge: string;
  badgeColor: string;
  icon: React.ElementType;
  iconColor: string;
  features: string[];
};

const SERVICES: BusinessService[] = [
  {
    id: "servicio-crear-empresa-usa",
    name: "Crear Empresa en Estados Unidos + EIN + DUNS",
    description: "Constituimos tu empresa en Estados Unidos, obtenemos su EIN ante el IRS y solicitamos su número DUNS. No incluye el pago al estado por crearla.",
    price: 150,
    marketPrice: 700,
    badge: "Empresa USA",
    badgeColor: "bg-indigo-50 text-indigo-700 border-indigo-200",
    icon: Building2,
    iconColor: "bg-indigo-50 text-indigo-600",
    features: ["Constitución de la empresa", "EIN (Número de Identificación Fiscal)", "Solicitud de número DUNS", "No incluye la tarifa del estado"],
  },
  {
    id: "servicio-diseno-web",
    name: "Diseño Web",
    description: "Tu propio sitio web profesional para presentar tu negocio y vender en línea. Más $20 USD al mes de mantenimiento.",
    price: 500,
    marketPrice: 2500,
    priceNote: "Desde",
    badge: "Sitio Web",
    badgeColor: "bg-blue-50 text-blue-700 border-blue-200",
    icon: Globe,
    iconColor: "bg-blue-50 text-blue-600",
    features: ["Diseño a la medida de tu marca", "Adaptado a celulares", "El precio final depende del alcance", "Mantenimiento: $20 USD / mes"],
  },
  {
    id: "servicio-identidad-visual",
    name: "Identidad Visual",
    description: "Logo, colores, tipografías y manual de marca para que tu negocio se vea profesional.",
    price: 500,
    marketPrice: 2000,
    priceNote: "Desde",
    badge: "Marca",
    badgeColor: "bg-pink-50 text-pink-700 border-pink-200",
    icon: Palette,
    iconColor: "bg-pink-50 text-pink-600",
    features: ["Diseño de logo", "Paleta de colores y tipografías", "Manual de marca"],
  },
  {
    id: "servicio-meta-business",
    name: "Configuración de Meta Business Suite",
    description: "Configuramos tu Meta Business Suite para administrar Facebook e Instagram de tu negocio.",
    price: 100,
    marketPrice: 300,
    badge: "Meta",
    badgeColor: "bg-sky-50 text-sky-700 border-sky-200",
    icon: Settings,
    iconColor: "bg-sky-50 text-sky-600",
    features: ["Cuenta comercial de Meta", "Conexión de Facebook e Instagram", "Configuración de accesos"],
  },
  {
    id: "servicio-redes-sociales",
    name: "Redes Sociales: Viralización y Ventas",
    description: "Gestión de tus redes sociales con estrategia de viralización y un sistema de ventas.",
    price: 800,
    marketPrice: 2500,
    priceNote: "/ mes",
    badge: "Mensual",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    icon: TrendingUp,
    iconColor: "bg-emerald-50 text-emerald-600",
    features: ["Estrategia de contenido", "Viralización", "Sistema de ventas"],
  },
  {
    id: "servicio-campana-publicitaria",
    name: "Campaña Publicitaria",
    description: "Creación y gestión de tu campaña publicitaria. No incluye el presupuesto de pauta.",
    price: 500,
    marketPrice: 1500,
    priceNote: "/ mes",
    badge: "Mensual",
    badgeColor: "bg-orange-50 text-orange-700 border-orange-200",
    icon: Megaphone,
    iconColor: "bg-orange-50 text-orange-600",
    features: ["Creación de la campaña", "Gestión y optimización", "No incluye presupuesto de pauta"],
  },
  {
    id: "servicio-taxes-empresa",
    name: "Taxes de Empresa",
    description: "Preparación de los impuestos de tu empresa. El precio puede cambiar según el volumen de facturas.",
    price: 500,
    marketPrice: 1500,
    priceNote: "Desde",
    badge: "Impuestos",
    badgeColor: "bg-amber-50 text-amber-700 border-amber-200",
    icon: Receipt,
    iconColor: "bg-amber-50 text-amber-600",
    features: ["Declaración de impuestos de la empresa", "Mejor precio si traes tus facturas organizadas", "El precio puede subir con muchas facturas"],
  },
  {
    id: "servicio-impuestos-personales",
    name: "Impuestos Personales",
    description: "Preparación y presentación de tu declaración de impuestos personal.",
    price: 70,
    marketPrice: 250,
    badge: "Impuestos",
    badgeColor: "bg-amber-50 text-amber-700 border-amber-200",
    icon: FileText,
    iconColor: "bg-amber-50 text-amber-600",
    features: ["Declaración personal", "Revisión de documentos", "Presentación de la declaración"],
  },
  {
    id: "servicio-nomina",
    name: "Servicio de Pago de Nómina",
    description: "Gestionamos el pago de nómina de tu empresa cada mes. Más $15 USD al mes por cada empleado.",
    price: 250,
    marketPrice: 450,
    priceNote: "/ mes",
    badge: "Mensual",
    badgeColor: "bg-teal-50 text-teal-700 border-teal-200",
    icon: Users,
    iconColor: "bg-teal-50 text-teal-600",
    features: ["Cálculo y pago de nómina", "$15 USD al mes por empleado", "Cobro de empleados según tu planilla"],
  },
];

/** Servicios ordenados del más barato al más caro (como se muestran en las tiendas). */
export const BUSINESS_SERVICES = [...SERVICES].sort((a, b) => a.price - b.price);

/** Servicios adicionales: solo se muestran en la tienda del portal (/portal/tienda). */
const PORTAL_EXTRA_SERVICES: BusinessService[] = [
  {
    id: "servicio-cuenta-bancaria",
    name: "Cuenta Bancaria Empresarial en EE. UU.",
    description: "Te acompañamos en la apertura de la cuenta bancaria de tu empresa. La aprobación final depende del banco.",
    price: 199,
    marketPrice: 500,
    badge: "Empresa USA",
    badgeColor: "bg-indigo-50 text-indigo-700 border-indigo-200",
    icon: Landmark,
    iconColor: "bg-indigo-50 text-indigo-600",
    features: ["Preparación de documentos", "Acompañamiento en la solicitud", "No incluye el depósito inicial"],
  },
  {
    id: "servicio-agente-registrado",
    name: "Agente Registrado y Dirección Comercial",
    description: "Agente registrado y dirección comercial en Estados Unidos para tu empresa durante un año.",
    price: 149,
    marketPrice: 350,
    priceNote: "/ año",
    badge: "Anual",
    badgeColor: "bg-indigo-50 text-indigo-700 border-indigo-200",
    icon: MapPin,
    iconColor: "bg-indigo-50 text-indigo-600",
    features: ["Agente registrado", "Dirección comercial en EE. UU.", "Recepción de documentos oficiales"],
  },
  {
    id: "servicio-telefono-whatsapp",
    name: "Teléfono Comercial de EE. UU. + WhatsApp Business",
    description: "Número de teléfono comercial de Estados Unidos configurado con WhatsApp Business.",
    price: 49,
    marketPrice: 150,
    badge: "Comunicación",
    badgeColor: "bg-sky-50 text-sky-700 border-sky-200",
    icon: Phone,
    iconColor: "bg-sky-50 text-sky-600",
    features: ["Número de EE. UU.", "WhatsApp Business configurado", "No incluye el costo mensual de la línea"],
  },
  {
    id: "servicio-contabilidad",
    name: "Contabilidad / Bookkeeping",
    description: "Llevamos la contabilidad de tu empresa cada mes, lista para tus impuestos.",
    price: 150,
    marketPrice: 400,
    priceNote: "/ mes",
    badge: "Mensual",
    badgeColor: "bg-amber-50 text-amber-700 border-amber-200",
    icon: Calculator,
    iconColor: "bg-amber-50 text-amber-600",
    features: ["Registro de ingresos y gastos", "Conciliación bancaria", "Reportes mensuales"],
  },
  {
    id: "servicio-registro-marca",
    name: "Registro de Marca (Trademark)",
    description: "Protegemos tu marca ante la USPTO. No incluye la tasa oficial (aprox. $350 por clase).",
    price: 399,
    marketPrice: 1000,
    badge: "Marca",
    badgeColor: "bg-pink-50 text-pink-700 border-pink-200",
    icon: BadgeCheck,
    iconColor: "bg-pink-50 text-pink-600",
    features: ["Búsqueda de disponibilidad", "Solicitud ante la USPTO", "No incluye la tasa oficial"],
  },
  {
    id: "servicio-tienda-online",
    name: "Tienda en Línea (E-commerce)",
    description: "Tu tienda en línea con Shopify o WooCommerce, lista para vender. No incluye el plan de la plataforma ni el dominio.",
    price: 900,
    marketPrice: 4000,
    priceNote: "Desde",
    badge: "Ventas",
    badgeColor: "bg-blue-50 text-blue-700 border-blue-200",
    icon: ShoppingCart,
    iconColor: "bg-blue-50 text-blue-600",
    features: ["Shopify o WooCommerce", "Catálogo de productos", "No incluye plan ni dominio"],
  },
  {
    id: "servicio-pasarela-pagos",
    name: "Pasarela de Pagos",
    description: "Configuramos Stripe, PayPal y cobros con stablecoins para que recibas pagos. No incluye las comisiones de cada pasarela.",
    price: 149,
    marketPrice: 400,
    badge: "Ventas",
    badgeColor: "bg-blue-50 text-blue-700 border-blue-200",
    icon: CreditCard,
    iconColor: "bg-blue-50 text-blue-600",
    features: ["Stripe y PayPal", "Cobros con stablecoins", "No incluye comisiones"],
  },
  {
    id: "servicio-seo-local",
    name: "Google Business Profile + SEO Local",
    description: "Tu negocio visible en Google y Google Maps, con posicionamiento local cada mes.",
    price: 249,
    marketPrice: 700,
    priceNote: "/ mes",
    badge: "Mensual",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    icon: Search,
    iconColor: "bg-emerald-50 text-emerald-600",
    features: ["Perfil de Google Business", "SEO local", "Reporte mensual"],
  },
  {
    id: "servicio-produccion-contenido",
    name: "Producción de Contenido",
    description: "Fotos, videos y reels profesionales para tus redes sociales cada mes.",
    price: 499,
    marketPrice: 1500,
    priceNote: "/ mes",
    badge: "Mensual",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    icon: Camera,
    iconColor: "bg-emerald-50 text-emerald-600",
    features: ["Fotos", "Videos", "Reels"],
  },
  {
    id: "servicio-email-marketing",
    name: "Email Marketing y Automatización",
    description: "Campañas de correo y automatizaciones para vender más. No incluye el plan de la plataforma de correo.",
    price: 249,
    marketPrice: 800,
    priceNote: "/ mes",
    badge: "Mensual",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    icon: Mail,
    iconColor: "bg-emerald-50 text-emerald-600",
    features: ["Campañas de correo", "Automatizaciones", "No incluye plan de la plataforma"],
  },
  {
    id: "servicio-chatbot-ia",
    name: "Chatbot / Asistente con IA",
    description: "Asistente con inteligencia artificial que atiende a tus clientes por WhatsApp y en tu web. Te registras en nuestra plataforma de IA y lo configuras con tu negocio.",
    price: 49.99,
    marketPrice: 150,
    badge: "IA",
    badgeColor: "bg-violet-50 text-violet-700 border-violet-200",
    icon: Bot,
    iconColor: "bg-violet-50 text-violet-600",
    features: ["WhatsApp y sitio web", "Entrenado con tu negocio", "Registro en nuestra plataforma de IA"],
  },
  {
    id: "servicio-crm",
    name: "CRM y Automatización de Ventas",
    description: "Organizamos tus clientes y automatizamos tu proceso de ventas. No incluye la licencia del CRM.",
    price: 399,
    marketPrice: 1500,
    badge: "Ventas",
    badgeColor: "bg-blue-50 text-blue-700 border-blue-200",
    icon: Workflow,
    iconColor: "bg-blue-50 text-blue-600",
    features: ["Configuración del CRM", "Embudo de ventas", "No incluye licencia"],
  },
  {
    id: "servicio-plan-negocios",
    name: "Plan de Negocios + Pitch Deck",
    description: "Tu plan de negocios y la presentación para inversionistas.",
    price: 699,
    marketPrice: 3000,
    badge: "Inversión",
    badgeColor: "bg-violet-50 text-violet-700 border-violet-200",
    icon: Presentation,
    iconColor: "bg-violet-50 text-violet-600",
    features: ["Plan de negocios", "Pitch deck", "Preparación para inversionistas"],
  },
  {
    id: "servicio-tokenizacion",
    name: "Tokenización / Token Propio",
    description: "Creamos el token de tu proyecto. Incluye llamada de diagnóstico; no incluye asesoría legal ni auditoría del contrato.",
    price: 3500,
    marketPrice: 15000,
    priceNote: "Desde",
    badge: "Inversión",
    badgeColor: "bg-violet-50 text-violet-700 border-violet-200",
    icon: Coins,
    iconColor: "bg-violet-50 text-violet-600",
    features: ["Llamada de diagnóstico", "Creación del token", "No incluye asesoría legal ni auditoría"],
  },
  {
    id: "servicio-mentoria",
    name: "Mentoría Empresarial 1 a 1",
    description: "Acompañamiento personalizado 1 a 1 para crear y hacer crecer tu empresa.",
    price: 2000,
    marketPrice: 5000,
    badge: "Mentoría",
    badgeColor: "bg-amber-50 text-amber-700 border-amber-200",
    icon: GraduationCap,
    iconColor: "bg-amber-50 text-amber-600",
    features: ["Sesiones 1 a 1", "Plan de acción para tu empresa", "Seguimiento personalizado"],
  },
  {
    id: "servicio-mentoria-completa",
    name: "Mentoría 1 a 1 + Paquete Empresarial",
    description: "Mentoría empresarial 1 a 1 junto con los servicios esenciales para lanzar tu empresa: registro, EIN y DUNS, banco, marca, presencia digital y cobros. Revisa en Ver detalles todo lo que incluye.",
    price: 5000,
    marketPrice: 13000,
    badge: "Paquete",
    badgeColor: "bg-amber-50 text-amber-700 border-amber-200",
    icon: Crown,
    iconColor: "bg-amber-50 text-amber-600",
    features: ["Mentoría empresarial 1 a 1", "Crear Empresa en EE. UU. + EIN + DUNS", "Agente Registrado y Dirección Comercial", "Cuenta Bancaria Empresarial en EE. UU.", "Teléfono Comercial de EE. UU. + WhatsApp Business", "Identidad Visual", "Registro de Marca (Trademark)", "Configuración de Meta Business Suite", "Diseño Web", "Pasarela de Pagos", "Chatbot / Asistente con IA", "No incluye tasas oficiales ni costos de terceros"],
  },
];

/** Tienda del portal: todos los servicios, del más barato al más caro. */
export const PORTAL_SERVICES = [...SERVICES, ...PORTAL_EXTRA_SERVICES].sort((a, b) => a.price - b.price);

/** Secciones de la tienda del portal. Dentro de cada sección se ordena del más barato al más caro. */
const PORTAL_SECTION_DEFINITIONS: { title: string; subtitle: string; ids: string[] }[] = [
  {
    title: "Para arrancar la empresa",
    subtitle: "Todo lo legal, fiscal y de marca para que tu empresa exista en Estados Unidos.",
    ids: [
      "servicio-crear-empresa-usa",
      "servicio-agente-registrado",
      "servicio-cuenta-bancaria",
      "servicio-telefono-whatsapp",
      "servicio-identidad-visual",
      "servicio-registro-marca",
      "servicio-impuestos-personales",
    ],
  },
  {
    title: "Para vender",
    subtitle: "Presencia digital, publicidad y herramientas para atraer clientes y cobrar.",
    ids: [
      "servicio-meta-business",
      "servicio-diseno-web",
      "servicio-pasarela-pagos",
      "servicio-seo-local",
      "servicio-campana-publicitaria",
      "servicio-produccion-contenido",
      "servicio-email-marketing",
      "servicio-chatbot-ia",
    ],
  },
  {
    title: "Para crecer",
    subtitle: "Organiza tus ventas, tus finanzas y tu equipo a medida que tu empresa crece.",
    ids: ["servicio-crm", "servicio-contabilidad", "servicio-nomina", "servicio-taxes-empresa"],
  },
  {
    title: "Escalada mundial",
    subtitle: "Lleva tu empresa al siguiente nivel: ventas globales, inversionistas, tokenización y mentoría.",
    ids: [
      "servicio-redes-sociales",
      "servicio-tienda-online",
      "servicio-plan-negocios",
      "servicio-mentoria",
      "servicio-tokenizacion",
      "servicio-mentoria-completa",
    ],
  },
];

export const PORTAL_SERVICE_SECTIONS = PORTAL_SECTION_DEFINITIONS.map((section) => ({
  title: section.title,
  subtitle: section.subtitle,
  services: PORTAL_SERVICES.filter((service) => section.ids.includes(service.id)),
}));
